sudo: required
services:
  - docker

before_install:
  - docker build -t miguelangeltorresfp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run miguelangeltorresfp/react-test npm run test

after_success:
  - docker build -t miguelangeltorresfp/multi-client ./client
  - docker build -t miguelangeltorresfp/multi-nginx ./nginx
  - docker build -t miguelangeltorresfp/multi-server ./server
  - docker build -t miguelangeltorresfp/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push theme to docker hub
  - docker push miguelangeltorresfp/multi-client
  - docker push miguelangeltorresfp/multi-nginx
  - docker push miguelangeltorresfp/multi-server
  - docker push miguelangeltorresfp/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-eu-west-1-633762040595"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
